name: Merged to Main

on:
  # Triggered when a pull request is closed and merged into the main branch
  pull_request:
    branches:
      - main
    types:
      - closed
  # Manually triggered workflow with inputs for title and body
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR Number"
        default: "200"
      title:
        description: "Title for the PR"
        default: "TEST | [Release] Stage to Main"
      body:
        type: string
        description: "Description for the PR"
        required: true

env:
  # Slack webhook secret
  CC_SLACK_WEBHOOK: ${{ secrets.CC_SLACK_WEBHOOK }}

jobs:
  # Job to handle merged pull requests
  merged_to_main:
    runs-on: ubuntu-latest
    # Run the job when a pull request is merged into main and not triggered manually
    if: ${{ github.event_name != 'workflow_dispatch' && github.event.pull_request.merged }}
    environment: cc-test-release
    env:
      # Environment variable to store pull request details
      EVENT_PR: ${{ toJson(github.event.pull_request) }}
    steps:
      # Checkout repository action
      - name: Checkout repository
        uses: actions/checkout@v4
      # Sending slack notification
      - name: Sending Notification - Slack
        uses: actions/github-script@v7
        with:
          script: |
            const sendSlackMessage = require('./.github/workflows/src/send-slack.js')
            sendSlackMessage(process.env.EVENT_PR,process.env.CC_SLACK_WEBHOOK)
  # Job to handle manually triggered workflow_dispatch events
  workflow_dispatch_event:
    runs-on: ubuntu-latest
    environment:
      name: cc-test-release
    # Run the job when the workflow is manually triggered
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      # Checkout repository action
      - name: Check repository
        uses: actions/checkout@v4
      - name: Print Description
        run: |
          echo ${{github.event.inputs.body}}
      # Sending slack notification
      - name: Sending Notification - Slack
        uses: actions/github-script@v7
        # Set environment variables for repository URL, PR number,PR title, and PR description
        env:
          REPO_URL: ${{github.event.repository.html_url}}
          PR_NUMBER: ${{github.event.inputs.pr_number}}
          PR_TITLE: ${{github.event.inputs.title}}
          PR_DESC: ${{github.event.inputs.body}}
        with:
          script: |
            const sendSlackMessage = require('./.github/workflows/src/send-slack.js')
            sendSlackMessage(JSON.stringify({
              number:process.env.PR_NUMBER, 
              html_url:process.env.REPO_URL+"/pull/"+process.env.PR_NUMBER, 
              title:process.env.PR_TITLE, 
              body:String(process.env.PR_DESC).split("\r\n").join("\n")
            }),process.env.CC_SLACK_WEBHOOK)
