name: On PR Closed

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true
        default: ""

env:
  PR_NUMBER: ${{ github.event.number }}
  CC_SLACK_WEBHOOK: ${{ secrets.CC_SLACK_WEBHOOK }}

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: cc-test-release
    env:
      EVENT_PR: ${{ toJson(github.event.pull_request) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Sending Notification - Slack
        uses: actions/github-script@v7
        with:
          script: |
            const sendSlackMessage = require('./.github/workflows/src/send-slack.js')
            sendSlackMessage(process.env.EVENT_PR,process.env.CC_SLACK_WEBHOOK)
