name: Merged to Main

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:
    inputs:
      title:
        description: "Title for the PR"
        default: "[Release] Stage to Main"
      body:
        description: "Description for the PR"
        required: true

env:
  CC_SLACK_WEBHOOK: ${{ secrets.CC_SLACK_WEBHOOK }}

jobs:
  merged_to_main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' && github.event.pull_request.merged == true }}
    environment: cc-test-release
    env:
      EVENT_PR: ${{ toJson(github.event.pull_request) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Sending Notification - Slack
        uses: actions/github-script@v7
        with:
          script: |
            const sendSlackMessage = require('./.github/workflows/src/send-slack.js')
            sendSlackMessage(process.env.EVENT_PR,process.env.CC_SLACK_WEBHOOK)
  workflow_dispatch_event:
    runs-on: ubuntu-latest
    environment:
      name: cc-test-release
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Check repository
        uses: actions/checkout@v4

      - name: Sending Notification - Slack
        uses: actions/github-script@v7
        env:
          REPO_URL: ${{github.event.repository.html_url}}
          PR_TITLE: ${{github.event.inputs.title}}
          PR_DESC: ${{github.event.inputs.body}}
        with:
          script: |
            const sendSlackMessage = require('./.github/workflows/src/send-slack.js')
            sendSlackMessage(JSON.stringify({
              number:12, 
              html_url:process.env.REPO_URL, 
              title:process.env.REPO_URL, 
              body:process.env.PR_DESC
            }),process.env.CC_SLACK_WEBHOOK)
