name: release-notification

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
