name: release-notification

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Print Title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "$PR_TITLE"
      - name: Print Body
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: echo "$PR_BODY"
      - run: |
          echo The PR was merged - #"$PR_NUMBER"
          echo The PR Event - "$PR_EVENT"
