name: release-notification

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

env:
  PR_NUMBER: ${{ github.event.number }}
  CC_SLACK_WEBHOOK: ${{ secrets.CC_SLACK_WEBHOOK }}

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: cc-test-release
    env:
      PR_BODY: ${{ github.event.pull_request.body }}
    steps:
      - name: Print Body
        run: echo "$PR_BODY"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Sending Notification - Slack
        uses: actions/github-script@v7
        with:
          script: |
            const sendSlackMessage = require('./.github/workflows/send-slack.js')
            sendSlackMessage(process.env.PR_BODY,process.env.CC_SLACK_WEBHOOK)
